DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS score;

CREATE TABLE team (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(10) NOT NULL,
  UNIQUE KEY (name),
  PRIMARY KEY (id)
);

CREATE TABLE score (
  id INT NOT NULL AUTO_INCREMENT,
  team_id INT NOT NULL,
  entry_date DATETIME NOT NULL,
  FOREIGN KEY (team_id) REFERENCES team(id),
  PRIMARY KEY (id)
)